kind = "api"
previewPath = "/api"
title = "Argus API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "API Server"
paths = ["/api"]

[services.development]
run = "cd argus && python main.py"

[services.production]

[services.production.build]
args = ["echo", "no-build-step"]

[services.production.run]
args = ["python", "argus/main.py"]

[services.production.run.env]
API_PORT = "8000"

[services.production.health.startup]
path = "/api/health"
